
##
## Name of our project and executable
##
TARGET =  chibios_template
TARGET_DIR = executable
LIBRARY = 0
CHIBIOS_RTOS_USE = 1
STARTUP_FILE = startup_stm32f4xx_chibios
#LDSCRIPT = $(SRC_DIR)/stm32_chibios.ld
LDSCRIPT = ../../RTOS/ChibiOS_2.6.1/os/ports/GCC/ARMCMx/STM32F4xx/ld/STM32F407xG.ld
include ../Makefile.stm32f4

