
##
## Name of our project and executable
##
TARGET = ucosii_template
TARGET_DIR = executable
LIBRARY = 0
UCOS_II_RTOS_USE = 1
STARTUP_FILE = startup_stm32f4xx_ucos_ii
include ../Makefile.stm32f4

