
##
## Name of our project and executable
##
TARGET =  freertos_template
TARGET_DIR = executable
LIBRARY = 0
FREE_RTOS_USE = 1
STARTUP_FILE = startup_stm32f4xx_freertos
LDSCRIPT = $(SRC_DIR)/stm32_freertos.ld
include ../Makefile.stm32f4

